services:
  backend:
    build: ./backend  # 添加 build 配置
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      GAME_IS_IN_DEV_MODE: "true"
    command: tail -f /dev/null

  frontend:
    build: ./frontend  # 添加 build 配置
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      GAME_IS_IN_DEV_MODE: "true"
    command: tail -f /dev/null
